/*
 * File: Main.java
 * -----------------------------------------------
 * Runs the program that run test environment
 * for the specified FPGA design file.
 * See the link below.
 *
 * TODO: Link to the help file.
 *       Also it can be great to use autogenerated
 *       java-doc.
 */
public class Main {

    public static void main(String[] args) {
        new Application();
    }

}
